package cu.academy.shared.enum_types;

public enum EnumTipoComision {
    SERVICIO_A_PORCIENTO, CORTESIA_AGENCIA, CORTESIA_CHOFER, COMISION_AGENCIA, COMISION_CLIENTE, COMISION_AGENCIA_CLIENTE,AYUDA_OPERADORA,
}
