package cu.academy.shared.enum_types;

public enum EnumModoPago {
    EFECTIVO, FONDO, TRANF_CHOFER, TRANF_AGENCIA, TRANF_CUP_AGENCIA,
    CHEQUE, PAYPAL, BIZUM, WISE, ZELLE, TROPIPAY, VISA, MASTERCARD, TRANF_MLC_CHOFER, EXTERIOR
}
