on:
  push:
    branches:
      - release

jobs:

  job-one:
    name: Build, push, deploy and update digital Ocean
    runs-on: ubuntu-latest
    steps:

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.RSA_KEY_DOCEAN_PRIVATE_SECRET }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -p 22 -H 164.92.71.78  >> ~/.ssh/known_hosts

      - uses: actions/checkout@v2

      - name: Set up OpenJDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Check Java Version
        run: java -version

      - name: Build JAR
        run: |
          ls -la
          mvn install
          ls -l target/

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: 164.92.71.78
          username: root
          key: ${{ secrets.RSA_KEY_DOCEAN_PRIVATE_SECRET }}
          port: 22
          source: "target/academy-api-rest-0.0.1-SNAPSHOT.jar"
          target: "/home/deploy/app/"

      - name: Connect to Digital Ocean via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 164.92.71.78
          username: root
          key: ${{ secrets.RSA_KEY_DOCEAN_PRIVATE_SECRET }}
          port: 22
          command_timeout: 1m
          script: |
            cd /home/deploy/app/target/
            pgrep java
            kill -9 $(pgrep java)
            java -Dspring.profiles.active=digitalOcean -jar academy-api-rest-0.0.1-SNAPSHOT.jar &
